from __future__ import annotations

from typing import Dict, List, Set

EXCLUDE_DIRS: Set[str] = {
    ".astro",
    ".hypothesis",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nitro",
    ".nox",
    ".nuxt",
    ".nx",
    ".output",
    ".pdm-build",
    ".pixi",
    ".pnp",
    ".pybuilder",
    ".pyre",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".serverless",
    ".svelte-kit",
    ".tanstack",
    ".tanstack-start",
    ".terraform",
    ".tox",
    ".turbo",
    ".vercel",
    ".vinxi",
    ".vite",
    ".wrangler",
    ".beads",
    ".code-state",
    ".git",
    ".next",
    ".venv",
    "__pypackages__",
    "ENV",
    "__pycache__",
    ".dart_tool",
    "build",
    "coverage",
    "dist",
    "env",
    "htmlcov",
    "node_modules",
    "out",
    "site-packages",
    "target",
    "vendor",
    "venv",
    "workspace",
}

QUALITY_MAX_FILES = 5000
ENTITY_AUTO_MAX_FILES = 2000
INCREMENTAL_DEP_DEPTH = 2
INCREMENTAL_DEP_LIMIT = 2000

FD_EXCLUDES: List[str] = [
    ".astro",
    ".hypothesis",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nitro",
    ".nox",
    ".nuxt",
    ".nx",
    ".output",
    ".pdm-build",
    ".pixi",
    ".pnp",
    ".pybuilder",
    ".pyre",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".serverless",
    ".svelte-kit",
    ".tanstack",
    ".tanstack-start",
    ".terraform",
    ".tox",
    ".turbo",
    ".vercel",
    ".vinxi",
    ".vite",
    ".wrangler",
    ".beads",
    ".code-state",
    ".git",
    ".next",
    ".venv",
    "__pypackages__",
    "ENV",
    "__pycache__",
    ".dart_tool",
    "build",
    "coverage",
    "dist",
    "env",
    "htmlcov",
    "node_modules",
    "out",
    "site-packages",
    "target",
    "vendor",
    "venv",
    "workspace",
]

RG_EXCLUDES: List[str] = [
    "!**/.astro/**",
    "!**/.hypothesis/**",
    "!**/.ipynb_checkpoints/**",
    "!**/.mypy_cache/**",
    "!**/.nitro/**",
    "!**/.nox/**",
    "!**/.nuxt/**",
    "!**/.nx/**",
    "!**/.output/**",
    "!**/.pdm-build/**",
    "!**/.pixi/**",
    "!**/.pnp/**",
    "!**/.pybuilder/**",
    "!**/.pyre/**",
    "!**/.pytest_cache/**",
    "!**/.pytype/**",
    "!**/.ruff_cache/**",
    "!**/.serverless/**",
    "!**/.svelte-kit/**",
    "!**/.tanstack/**",
    "!**/.tanstack-start/**",
    "!**/.terraform/**",
    "!**/.tox/**",
    "!**/.turbo/**",
    "!**/.vercel/**",
    "!**/.vinxi/**",
    "!**/.vite/**",
    "!**/.wrangler/**",
    "!**/.beads/**",
    "!**/.code-state/**",
    "!**/.git/**",
    "!**/.next/**",
    "!**/.venv/**",
    "!**/__pypackages__/**",
    "!**/ENV/**",
    "!**/__pycache__/**",
    "!**/.dart_tool/**",
    "!**/build/**",
    "!**/coverage/**",
    "!**/dist/**",
    "!**/env/**",
    "!**/htmlcov/**",
    "!**/node_modules/**",
    "!**/out/**",
    "!**/site-packages/**",
    "!**/target/**",
    "!**/vendor/**",
    "!**/venv/**",
    "!**/workspace/**",
    "!**/*.egg",
    "!**/*.py[cod]",
    "!**/*.pyd",
    "!**/*.so",
    "!**/*.tsbuildinfo",
    "!**/.coverage",
    "!**/.coverage.*",
    "!**/.dmypy.json",
    "!**/.pdm-python",
    "!**/.pnp.cjs",
    "!**/.pnp.js",
    "!**/.yarn/install-state.gz",
    "!**/coverage.xml",
    "!**/MANIFEST",
    "!**/next-env.d.ts",
    "!**/*.egg-info/**",
    "!**/*.profraw",
]

TS_GLOBS = ["**/*.ts", "!**/*.d.ts"] + RG_EXCLUDES
TSX_GLOBS = ["**/*.tsx"] + RG_EXCLUDES
JS_GLOBS = ["**/*.js", "!**/*.min.js", "**/*.mjs", "**/*.cjs"] + RG_EXCLUDES
JSX_GLOBS = ["**/*.jsx"] + RG_EXCLUDES
PY_GLOBS = ["**/*.py"] + RG_EXCLUDES
RS_GLOBS = ["**/*.rs"] + RG_EXCLUDES

UNSUPPORTED_LANG_EXTS: Dict[str, str] = {
    ".java": "java",
    ".kt": "kotlin",
    ".cs": "csharp",
    ".c": "c",
    ".cc": "cpp",
    ".cxx": "cpp",
    ".cpp": "cpp",
    ".h": "c",
    ".hpp": "cpp",
    ".swift": "swift",
    ".rb": "ruby",
    ".php": "php",
    ".scala": "scala",
    ".lua": "lua",
    ".r": "r",
    ".m": "objectivec",
    ".mm": "objectivec++",
    ".sql": "sql",
}

MONOREPO_MARKERS: Dict[str, str] = {
    "pnpm-workspace.yaml": "pnpm",
    "pnpm-workspace.yml": "pnpm",
    "lerna.json": "lerna",
    "turbo.json": "turbo",
    "rush.json": "rush",
    "nx.json": "nx",
    "workspace.json": "nx",
}

PACKAGE_MANIFESTS: Dict[str, str] = {
    "package.json": "node",
    "pyproject.toml": "python",
    "setup.py": "python",
    "setup.cfg": "python",
    "Cargo.toml": "rust",
    "go.mod": "go",
}

CONFIG_FILES: Set[str] = {
    "package.json",
    "pyproject.toml",
    "requirements.txt",
    "requirements-dev.txt",
    "setup.py",
    "setup.cfg",
    "tsconfig.json",
    "vite.config.js",
    "vite.config.ts",
    "webpack.config.js",
    "webpack.config.ts",
    "next.config.js",
    "next.config.ts",
    "dockerfile",
    "docker-compose.yml",
    "makefile",
    "cargo.toml",
    "go.mod",
    "gemfile",
    "skill.spec.json",
    "repomap.json",
    ".repomap.json",
}

REPOMAP_CONFIG_FILES = ("repomap.json", ".repomap.json")

ENTRYPOINT_NAME_ROLES: Dict[str, str] = {
    "main.ts": "cli",
    "main.tsx": "ui",
    "main.py": "cli",
    "main.go": "cli",
    "main.rs": "cli",
    "__main__.py": "cli",
    "cli.ts": "cli",
    "cli.py": "cli",
    "cli.go": "cli",
    "cli.rs": "cli",
    "app.ts": "http",
    "app.tsx": "ui",
    "app.go": "http",
    "app.rs": "http",
    "server.ts": "http",
    "server.tsx": "http",
    "server.go": "http",
    "server.rs": "http",
    "app.py": "http",
    "server.py": "http",
    "wsgi.py": "http",
    "asgi.py": "http",
    "manage.py": "http",
    "worker.py": "worker",
    "workers.py": "worker",
    "tasks.py": "worker",
    "celery.py": "worker",
    "job.py": "worker",
    "queue.py": "worker",
}

ENTRYPOINT_NAMES = set(ENTRYPOINT_NAME_ROLES)


def ast_globs_for(lang: str) -> List[str]:
    if lang == "ts":
        return TS_GLOBS
    if lang == "tsx":
        return TSX_GLOBS
    if lang in {"js", "javascript"}:
        return JS_GLOBS
    if lang == "jsx":
        return JSX_GLOBS
    if lang == "python":
        return PY_GLOBS
    if lang == "rust":
        return RS_GLOBS
    return []
