from __future__ import annotations

from typing import Dict
import argparse

PROFILE_PRESETS: Dict[str, Dict[str, object]] = {
    "fast": {
        "codeql": "off",
        "budget": 4000,
        "budget_margin": 0.85,
        "max_files": 20,
        "max_symbols": 2,
        "max_edges": 25,
        "max_sig_len": 60,
        "dense": True,
        "dir_depth": 0,
        "diagrams": "off",
        "include_routes": False,
        "api_contracts": False,
        "static_traces": False,
        "trace_depth": 2,
        "trace_max": 3,
        "flow_symbols": False,
        "semantic_cluster": False,
        "doc_quality": False,
        "diagram_nodes": 6,
        "diagram_edges": 8,
        "artifacts": "standard",
        "explain_ranking": False,
    },
    "balanced": {
        "codeql": "off",
        "budget": 20000,
        "budget_margin": 0.85,
        "dense": True,
        "dir_depth": 3,
        "diagrams": "compact+sequence",
        "include_routes": True,
        "routes_limit": 24,
        "api_contracts": True,
        "static_traces": True,
        "trace_depth": 3,
        "trace_max": 6,
        "max_files": 60,
        "max_symbols": 4,
        "max_edges": 120,
        "diagram_nodes": 8,
        "diagram_edges": 12,
        "section_budgets": {
            "SUMMARY": 0.08,
            "FILES": 0.30,
            "ENTRYPOINTS": 0.10,
            "ENTRYPOINT_GROUPS": 0.06,
            "ENTRY_DETAILS": 0.07,
            "ROUTES": 0.08,
            "API_CONTRACTS": 0.06,
            "ENTITIES": 0.08,
            "FLOWS": 0.08,
            "STATIC_TRACES": 0.06,
            "TRACE_GRAPH": 0.06,
            "QUALITY": 0.04,
            "DIAGRAM": 0.06,
            "DOCS": 0.03,
            "WARNINGS": 0.02,
            "LIMITS": 0.02,
        },
        "artifacts": "standard",
        "explain_ranking": False,
    },
    "deep": {
        "codeql": "auto",
        "budget": 80000,
        "budget_margin": 0.85,
        "dense": True,
        "dir_depth": 3,
        "diagrams": "compact+sequence",
        "include_routes": True,
        "routes_limit": 48,
        "artifacts": "full",
        "explain_ranking": True,
        "reuse_codeql_db": True,
        "keep_codeql_db": True,
        "doc_quality": True,
        "semantic_cluster": True,
        "api_contracts": True,
        "call_chains": True,
        "static_traces": True,
        "trace_depth": 4,
        "trace_max": 12,
        "flow_symbols": True,
        "max_files": 120,
        "max_symbols": 8,
        "max_edges": 250,
        "max_sig_len": 120,
        "diagram_nodes": 12,
        "diagram_edges": 18,
        "section_budgets": {
            "SUMMARY": 0.06,
            "FILES": 0.40,
            "ENTRYPOINTS": 0.10,
            "ENTRYPOINT_GROUPS": 0.06,
            "ENTRY_DETAILS": 0.08,
            "ROUTES": 0.08,
            "API_CONTRACTS": 0.07,
            "ENTITIES": 0.09,
            "FLOWS": 0.09,
            "STATIC_TRACES": 0.08,
            "TRACE_GRAPH": 0.07,
            "QUALITY": 0.05,
            "DIAGRAM": 0.06,
            "DOCS": 0.05,
            "DOCS_QUALITY": 0.03,
            "CALL_CHAINS": 0.03,
            "WARNINGS": 0.02,
            "LIMITS": 0.02,
        },
    },
}


def apply_profile(args: argparse.Namespace, profile: str) -> None:
    preset = PROFILE_PRESETS.get(profile)
    if not preset:
        return
    for key, value in preset.items():
        setattr(args, key, value)


def apply_quick_preset(args: argparse.Namespace) -> None:
    apply_profile(args, "fast")
